"""posts table

Revision ID: 748f530ce955
Revises: 258f10ab8819
Create Date: 2025-06-27 18:40:32.503441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748f530ce955'
down_revision = '258f10ab8819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_user_id'))
        batch_op.drop_index(batch_op.f('ix_tables_timestamp'))

    op.drop_table('tables')
    # ### end Alembic commands ###
