"""post 'timestamp' renamed to 'added_at'

Revision ID: a303092f540e
Revises: 2cc546eaed28
Create Date: 2025-06-28 19:35:39.838703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a303092f540e'
down_revision = '2cc546eaed28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_posts_timestamp'))
        batch_op.create_index(batch_op.f('ix_posts_added_at'), ['added_at'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_posts_added_at'))
        batch_op.create_index(batch_op.f('ix_posts_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###
